workflows:
  ios-app-preview:
    name: iOS App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
    scripts:
      - name: Hard Reset and Build iOS Simulator
        script: |
          # 1. Clean Flutter
          flutter clean
          flutter pub get
          
          # 2. Patch FFmpeg binary for Simulator (fixes "built for iOS" dylib error)
          FFMPEG_BIN=$(find "$HOME/.pub-cache" -path "*/ffmpeg_kit_flutter_new*/ios/Frameworks/ffmpegkit.framework/ffmpegkit" -type f 2>/dev/null | head -1)
          if [ -f "$FFMPEG_BIN" ]; then
            echo "🔧 Patching FFmpeg binary at: $FFMPEG_BIN"
            xcrun vtool -arch arm64 -set-build-version 7 15.1 15.1 -replace "$FFMPEG_BIN" -output "$FFMPEG_BIN" 2>/dev/null || true
            echo "✅ FFmpeg patched for simulator"
          else
            echo "⚠️ FFmpeg binary not found in pub cache, skipping patch"
          fi
          
          # 3. Hard Reset CocoaPods
          cd ios
          pod deintegrate
          rm -rf Pods build Podfile.lock .symlinks/plugins
          pod install --repo-update
          
          # 4. Return and Build
          cd ..
          flutter build ios --simulator --debug --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com

  android-app-preview:
    name: Android App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Hard Reset and Build APK
        script: |
          # 1. Clean Flutter
          flutter clean
          flutter pub get
          
          # 2. Build APK
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com
