workflows:
  ios-app-preview:
    name: iOS App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
    scripts:
      - name: Hard Reset and Build iOS Simulator
        script: |
          # 1. Clean Flutter
          flutter clean
          flutter pub get
          
          # 2. Patch ALL FFmpeg framework binaries for Simulator
          # FFmpeg ships multiple frameworks (ffmpegkit, libavcodec, libavformat, etc.)
          # All must be re-tagged from iOS (platform 2) to Simulator (platform 7)
          FFMPEG_FW_DIR=$(ls -d $HOME/.pub-cache/hosted/pub.dev/ffmpeg_kit_flutter_new-*/ios/Frameworks 2>/dev/null | head -1)
          if [ -d "$FFMPEG_FW_DIR" ]; then
            echo "🔧 Found FFmpeg frameworks at: $FFMPEG_FW_DIR"
            for fw in "$FFMPEG_FW_DIR"/*.framework; do
              binary_name=$(basename "$fw" .framework)
              binary="$fw/$binary_name"
              if [ -f "$binary" ]; then
                echo "  Patching: $binary_name"
                xcrun vtool -arch arm64 -set-build-version 7 15.1 15.1 -replace "$binary" -output "$binary" 2>/dev/null || true
              fi
            done
            echo "✅ All FFmpeg frameworks patched for simulator"
          else
            echo "⚠️ FFmpeg frameworks directory not found, skipping patch"
          fi
          
          # 3. Hard Reset CocoaPods
          cd ios
          pod deintegrate
          rm -rf Pods build Podfile.lock .symlinks/plugins
          pod install --repo-update
          
          # 4. Return and Build
          cd ..
          flutter build ios --simulator --debug --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com

  android-app-preview:
    name: Android App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Hard Reset and Build APK
        script: |
          # 1. Clean Flutter
          flutter clean
          flutter pub get
          
          # 2. Build APK
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com
