workflows:
  ios-app-preview:
    name: iOS App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..
      - name: Flutter build iOS Simulator
        script: | 
          flutter build ios --simulator --debug --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com # Replaced with a likely email based on corpus name, user should update if different

  android-app-preview:
    name: Android App Preview
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..
      - name: Flutter build APK
        script: | 
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - polashdas5322@gmail.com
